services:
  kwp:
    image: tinyops/kwp:0.7.0
    container_name: kwp
    restart: unless-stopped
    env_file: .env
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
      - ./config.yml:/app/config.yml
